project_id = "mrrdrtbarxaacmlzvgne"

[functions.raffle-offer]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.aesthetic-analysis]
verify_jwt = true

[functions.cosmetic-analyzer]
verify_jwt = true

[functions.scrape-website]
verify_jwt = true

[functions.ai-knowledge-chat]
verify_jwt = false

[functions.spin-to-win]
verify_jwt = false

[functions.analyze-skin]
verify_jwt = false

[functions.analyze-hair]
verify_jwt = false

[functions.analyze-skin-lesion]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.ai-skin-consultation]
verify_jwt = false

[functions.ai-voice-consultation]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false
