project_id = "mrrdrtbarxaacmlzvgne"

[functions.raffle-offer]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.aesthetic-analysis]
verify_jwt = true

[functions.cosmetic-analyzer]
verify_jwt = true

[functions.scrape-website]
verify_jwt = true

[functions.ai-knowledge-chat]
verify_jwt = false

[functions.spin-to-win]
verify_jwt = false
