// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrrdrtbarxaacmlzvgne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ycmRydGJhcnhhYWNtbHp2Z25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2NTU4NTAsImV4cCI6MjA1MDIzMTg1MH0.8TFJEx3PeGOLye-MOABPYdcu_8CqoUV6FhthuDL3EJo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);