// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzncehvnyelngwznukud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6bmNlaHZueWVsbmd3em51a3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDQ1MjcsImV4cCI6MjA2NjM4MDUyN30.TsF9zjgRnLuf9oWxgn8E2aikX5KFw7dPbLe5jHOKPvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);